-- Rename frames based on aspect ratio and type
-- This migration updates the names of existing frames to be more descriptive

UPDATE public.canva_frames SET name = 'Tall Portrait 1' WHERE name = 'Canva 1';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 14' WHERE name = 'Canva 14';
UPDATE public.canva_frames SET name = 'Portrait (Decorative) 15' WHERE name = 'Canva 15';
UPDATE public.canva_frames SET name = 'Tall Portrait 2' WHERE name = 'Canva 2';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 24' WHERE name = 'Canva 24';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 25' WHERE name = 'Canva 25';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 26' WHERE name = 'Canva 26';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 27' WHERE name = 'Canva 27';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 28' WHERE name = 'Canva 28';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 29' WHERE name = 'Canva 29';
UPDATE public.canva_frames SET name = 'Slim Vertical 3' WHERE name = 'Canva 3';
UPDATE public.canva_frames SET name = 'Tall Portrait (Decorative) 30' WHERE name = 'Canva 30';
UPDATE public.canva_frames SET name = 'Tall Portrait 4' WHERE name = 'Canva 4';
UPDATE public.canva_frames SET name = 'Square 5' WHERE name = 'Canva 5';
UPDATE public.canva_frames SET name = 'Square (Complex) 1' WHERE name = 'Canva Artboard 1';
UPDATE public.canva_frames SET name = 'Landscape 10' WHERE name = 'Canva Artboard 10';
UPDATE public.canva_frames SET name = 'Tall Portrait (Complex) 100' WHERE name = 'Canva Artboard 100';
UPDATE public.canva_frames SET name = 'Tall Portrait (Complex) 102' WHERE name = 'Canva Artboard 102';
UPDATE public.canva_frames SET name = 'Tall Portrait (Complex) 103' WHERE name = 'Canva Artboard 103';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 104' WHERE name = 'Canva Artboard 104';
UPDATE public.canva_frames SET name = 'Tall Portrait 105' WHERE name = 'Canva Artboard 105';
UPDATE public.canva_frames SET name = 'Tall Portrait (Complex) 106' WHERE name = 'Canva Artboard 106';
UPDATE public.canva_frames SET name = 'Tall Portrait 107' WHERE name = 'Canva Artboard 107';
UPDATE public.canva_frames SET name = 'Tall Portrait 108' WHERE name = 'Canva Artboard 108';
UPDATE public.canva_frames SET name = 'Portrait 11' WHERE name = 'Canva Artboard 11';
UPDATE public.canva_frames SET name = 'Square 12' WHERE name = 'Canva Artboard 12';
UPDATE public.canva_frames SET name = 'Portrait 13' WHERE name = 'Canva Artboard 13';
UPDATE public.canva_frames SET name = 'Portrait 14' WHERE name = 'Canva Artboard 14';
UPDATE public.canva_frames SET name = 'Square 15' WHERE name = 'Canva Artboard 15';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 16' WHERE name = 'Canva Artboard 16';
UPDATE public.canva_frames SET name = 'Square 17' WHERE name = 'Canva Artboard 17';
UPDATE public.canva_frames SET name = 'Square 18' WHERE name = 'Canva Artboard 18';
UPDATE public.canva_frames SET name = 'Landscape 19' WHERE name = 'Canva Artboard 19';
UPDATE public.canva_frames SET name = 'Portrait 2' WHERE name = 'Canva Artboard 2';
UPDATE public.canva_frames SET name = 'Basic Vertical 20' WHERE name = 'Canva Artboard 20';
UPDATE public.canva_frames SET name = 'Basic Square 21' WHERE name = 'Canva Artboard 21';
UPDATE public.canva_frames SET name = 'Square (Complex) 22' WHERE name = 'Canva Artboard 22';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 23' WHERE name = 'Canva Artboard 23';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 24' WHERE name = 'Canva Artboard 24';
UPDATE public.canva_frames SET name = 'Square 25' WHERE name = 'Canva Artboard 25';
UPDATE public.canva_frames SET name = 'Square 26' WHERE name = 'Canva Artboard 26';
UPDATE public.canva_frames SET name = 'Portrait 27' WHERE name = 'Canva Artboard 27';
UPDATE public.canva_frames SET name = 'Basic Rectangle 28' WHERE name = 'Canva Artboard 28';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 29' WHERE name = 'Canva Artboard 29';
UPDATE public.canva_frames SET name = 'Square 3' WHERE name = 'Canva Artboard 3';
UPDATE public.canva_frames SET name = 'Square 30' WHERE name = 'Canva Artboard 30';
UPDATE public.canva_frames SET name = 'Portrait 31' WHERE name = 'Canva Artboard 31';
UPDATE public.canva_frames SET name = 'Landscape 32' WHERE name = 'Canva Artboard 32';
UPDATE public.canva_frames SET name = 'Square 33' WHERE name = 'Canva Artboard 33';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 34' WHERE name = 'Canva Artboard 34';
UPDATE public.canva_frames SET name = 'Square 35' WHERE name = 'Canva Artboard 35';
UPDATE public.canva_frames SET name = 'Square 36' WHERE name = 'Canva Artboard 36';
UPDATE public.canva_frames SET name = 'Square (Complex) 37' WHERE name = 'Canva Artboard 37';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 38' WHERE name = 'Canva Artboard 38';
UPDATE public.canva_frames SET name = 'Square 39' WHERE name = 'Canva Artboard 39';
UPDATE public.canva_frames SET name = 'Portrait 4' WHERE name = 'Canva Artboard 4';
UPDATE public.canva_frames SET name = 'Square 40' WHERE name = 'Canva Artboard 40';
UPDATE public.canva_frames SET name = 'Square (Complex) 41' WHERE name = 'Canva Artboard 41';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 42' WHERE name = 'Canva Artboard 42';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 43' WHERE name = 'Canva Artboard 43';
UPDATE public.canva_frames SET name = 'Square (Complex) 44' WHERE name = 'Canva Artboard 44';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 45' WHERE name = 'Canva Artboard 45';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 46' WHERE name = 'Canva Artboard 46';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 47' WHERE name = 'Canva Artboard 47';
UPDATE public.canva_frames SET name = 'Tall Portrait (Complex) 48' WHERE name = 'Canva Artboard 48';
UPDATE public.canva_frames SET name = 'Square (Complex) 49' WHERE name = 'Canva Artboard 49';
UPDATE public.canva_frames SET name = 'Landscape 5' WHERE name = 'Canva Artboard 5';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 50' WHERE name = 'Canva Artboard 50';
UPDATE public.canva_frames SET name = 'Square 51' WHERE name = 'Canva Artboard 51';
UPDATE public.canva_frames SET name = 'Square (Complex) 52' WHERE name = 'Canva Artboard 52';
UPDATE public.canva_frames SET name = 'Landscape (Complex) 53' WHERE name = 'Canva Artboard 53';
UPDATE public.canva_frames SET name = 'Square (Complex) 54' WHERE name = 'Canva Artboard 54';
UPDATE public.canva_frames SET name = 'Square (Complex) 55' WHERE name = 'Canva Artboard 55';
UPDATE public.canva_frames SET name = 'Portrait 56' WHERE name = 'Canva Artboard 56';
UPDATE public.canva_frames SET name = 'Square 57' WHERE name = 'Canva Artboard 57';
UPDATE public.canva_frames SET name = 'Square (Complex) 59' WHERE name = 'Canva Artboard 59';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 6' WHERE name = 'Canva Artboard 6';
UPDATE public.canva_frames SET name = 'Portrait (Complex) 62' WHERE name = 'Canva Artboard 62';
UPDATE public.canva_frames SET name = 'Landscape 7' WHERE name = 'Canva Artboard 7';
UPDATE public.canva_frames SET name = 'Landscape 8' WHERE name = 'Canva Artboard 8';
UPDATE public.canva_frames SET name = 'Landscape 9' WHERE name = 'Canva Artboard 9';
